name: humanitarian_icons_test
description: Humanitarian Icons Test App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  humanitarian_icons:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
