name: humanitarian_icons
description: Humanitarian Icons package.
version: 0.0.1
author: Dhruvil Patel
homepage: https://github.com/dhruvilp/humanitarian_icons

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
   fonts:
     - family: HumanitarianIcons
       fonts:
         - asset: fonts/Humanitarian-Icons-v02.ttf
