name: etriage
description: Tech to Protect Challenge 2019 (contest no. 10)
version: 1.0.0+1
authors:
  - Dhruvil Patel (Github= dhruvilp)
  - Paul John (Github= PJprogrammer)

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application. Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  groovin_material_icons: ^1.1.6
  humanitarian_icons: ^0.1.0
  font_awesome_flutter: ^8.5.0
  flutter_bloc: ^3.2.0
  equatable: ^1.0.3
  qr_code_scanner: ^0.0.12
#  flutter_barcode_scanner: ^0.1.7
  dio: ^3.0.8
  http: ^0.12.0+4
  location: ^2.3.5
  google_maps_flutter: ^0.5.22
  flutter_speech: ^1.1.0
  provider: ^4.0.2
  path_provider: ^1.4.0
#  shared_preferences: ^0.5.6
  flutter_secure_storage: ^3.3.1+1
  crypto: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf